apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kafka-ui.fullname" . }} 
  namespace: {{ .Release.Namespace }}

spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "kafka-ui.fullname" . }}
    weight: 100
  wildcardPolicy: None